### ISSUE TITLE
Emulating nested settings

### ISSUE THREAD

**Issue by shreyasbharath** [entwanderer/yaml_extend#2]
Hi,

I was trying to use your gem in the following fashion -

`nested_config.yml`
```yaml
options:
  extends: 'child_config.yml'
```

`child_config.yml`
```yaml
blah: 'blah'
```

I want to be able to access the config like so `config.options.blah` rather than `config.blah` because I put the `extends` underneath the `options` key. Maybe I am doing something wrong? How do I achieve this?

Also, can you add `multiple` extends in a file?

**Comment by entwanderer** [comment]
By default you have to write the keyword for extending (by default: *extends*) on top level.

You can overwrite the default key by the second parameter, but only a string for top level.
```
YAML.ext_load_file(yaml_path, inheritance_key='extends', extend_existing_arrays=true, config = {})
```
I will take your example as feature request and will check if implementing support for nested configurations makes sense. A solution might look like a parameter of format 'options.extends' or ['options']['extends'].



Yes, you can extend by multiple files by defining a list instead a string:

```
extends:
  - 'super_config.yml'
  - 'another_super_config.yml'
```

**Comment by entwanderer** [comment]
You are welcome!

I just created the new release 0.1.0 with the asked feature.

You now can specify nested inheritance keys, for your example you have to write:
```
YAML.ext_load_file('nested_config.yml',['options','extends'])
```
Please report to me, if it works as you expected.

**Comment by shreyasbharath** [comment]
Here's an example -

```
settings_group_1:
  settings_sub_group_1: `extends settings_sub_group_1.yml
```

In another file, it might be something like

```
settings_group_2:
  settings_sub_group_2: `extends settings_sub_group_2.yml
```

Does that make sense? There won't be a single custom key but multiple custom keys (all of which will be a pain to manually specify).

**Comment by entwanderer** [comment]
Thank you for your feedback.

I'm not exactly sure, how your example looks like in a real situation.
It looks like, if your problem can already be solved with the available functionality.

But to ensure this, or if there may be a real need for solving your problem in another way:
Could you provide a more detailed real world example with pseudo data, including all the files? (including the resulting file!)

**Comment by shreyasbharath** [comment]
Sorry about the delayed reply, been held up by other things.

I'll try to describe an example in our project.

We have lots of build configs in our project for various compilers (gcc, clang etc.) and each one of these configurations have `warning options`, `compile options` etc. These are duplicated in every single config and we have to modify each config any time we change one of the options. This is rather annoying.

This is what it looks like -

```
---------
compiler:
  compile_options:
    - option_1
    - option_2
    ...
  warning_options:
    - option_1
    - option_2
    ...
```

What I want to do is something like below for every single build config.

```
---------
compiler:
  defines: `extends compiler_defines.yml`
  compile_options: `extends compile_options.yml`
  warning_options: `extends warning_options.yml`
linker:
  link_options: `extends link_options.yml`
```

I hope that makes more sense now? Let me know if you want me to clarify anything.

**Comment by entwanderer** [comment]
No Problem, same here: got ill, but feel better now. ;)

If I understand your problem correctly, you can already solve your problem this way:
```yaml
# compile_options.yml
---------
compiler:
  compile_options:
    - option_1
    - option_2
```

```yaml
# warning_options.yml
---------
compiler:
  warning_options:
    - option_1
    - option_2
```

```yaml
# compiler_defines.yml
---------
compiler:
  defines:
    - define_1
    - define_2
```

And extend them in the final or pre-final configuration file:
```yaml
# compiler.yml
---------
extends:
  - 'compile_options.yml'
  - 'warning_options.yml'
  - 'compiler_defines.yml'
compiler:
  compile_options:
    - option_3
  another_option:
    - option_1
some_global_option: true
```

This will result in the following configuration:
```yaml
---------
compiler:
  compile_options:
    - option_1
    - option_2
    - option_3
  warning_options:
    - option_1
    - option_2
  defines:
    - define_1
    - define_2
  another_option:
    - option_1
some_global_option: true
```

Isn't it, what you wanted to achieve?
