### ISSUE TITLE
Boolean keys with value "true" in base YAML are not overwritten by "false" in extended YAMLs

### ISSUE THREAD

**Issue by MohamedAsan** [entwanderer/yaml_extend#3]
For example,

Let the base YAML be:
```yaml
# base.yml
alpha: true
beta: false
gamma: true
data:
    delta: false
    kappa: true
    theta: false
```

Let the extended YAML be:
```yaml
# extended.yml
extends: 'base.yml'
alpha: false
beta: true
data:
    delta: true
    kappa: false
```

When you call

```ruby
YAML.ext_load_file 'extended.yml'
```

the returned YAML value results in

```yaml
alpha: true
beta: true
gamma: true
data:
    delta: true
    kappa: true
    theta: false
```

The values of **alpha** and **kappa** should actually be _**false**_ since they are over-written in extended YAML

<img width="640" alt="yaml_extend_issue" src="https://user-images.githubusercontent.com/29650842/40266274-b8256936-5b65-11e8-918e-7f837959c8af.png">
